import type { Metadata } from 'next';
import StyledJsxRegistry from './registry';

export const metadata: Metadata = {
  title: 'Boilerplate Next.js + TailwindCSS + Styled Components',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  themeColor: '#000000'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" suppressHydrationWarning={true}>
      <body>
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  );
}
